name: Build Plugin Releasae

on:
  push:
    tags:
      - 'v*'
      - '!*test*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        id: build_gradle
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin

      - name: Get Build Result
        id: get_filepath
        run: |
          output="$(ls build/distributions/MayaCharm-*.zip)"
          echo "::set-output name=path::${output}"
          echo "::set-output name=name::$(basename ${output})"

      - name: Get Changelog Entry
        id: chagelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.changelog_reader.outputs.log_entry }}
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_filepath.outputs.path }}
          asset_name: ${{ steps.get_filepath.outputs.name }}
          asset_content_type: application/zip
