# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Plugin Releasae

on:
  push:
    tags:
      - 'v*'
      - '!*test*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew buildPlugin
    
    - name: Get Changelog Entry
      id: chagelog_reader
      uses: mindsers/changelog-reader-action@v1.1.0
      with:
        version: ${{ github.ref }}
        path: ./CHANGELOG.md
       
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITGUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{steps.changelog_reader.outputs.log_entry }}
        prerelease: false
        
    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/distributions/MayaCharm${{ github.ref[1:] }}.zip
        asset_name: MayaCharm${{ github.ref[1:] }}.zip
        asset_content_type: application/zip
